sonar.projectKey=martinezfuentesadrian.dev
sonar.projectName=martinezfuentesadrian.dev
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/public/**,**/*.config.js,**/*.config.mjs,**/dist/**,**/build/**,next-env.d.ts,**/*.d.ts
